# In hollywood_editor/content_engine.py

import os
import openai
import asyncio
from typing import List

# Assuming project.py is in the same directory
from .project import ContentType

class GenerativeContentEngine:
    """
    Uses Large Language Models to generate video scripts and extract keywords.
    """
    def __init__(self):
        """
        Initializes the content engine and sets the OpenAI API key.
        Expects the API key to be in an environment variable 'OPENAI_API_KEY'.
        """
        self.api_key = os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError("OPENAI_API_KEY environment variable not set.")
        openai.api_key = self.api_key

    async def generate_script(self, prompt: str, content_type: ContentType, duration_seconds: int) -> str:
        """
        Generates a complete video script from a prompt using an LLM.

        Args:
            prompt: The user's initial idea or prompt.
            content_type: The type of content (e.g., Educational, Entertainment).
            duration_seconds: The target duration of the video.

        Returns:
            A string containing the generated video script.
        """
        system_prompt = f"""
        You are a world-class scriptwriter for viral social media videos.
        Your task is to write a script for a {duration_seconds}-second video.
        The content type is {content_type.value}.
        The script must be highly engaging, concise, and include a strong hook within the first 3 seconds.
        Structure the output clearly, indicating scenes, voiceover (VO), and on-screen text (TEXT).
        """
        
        try:
            response = await openai.ChatCompletion.acreate(
                model="gpt-4-turbo",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            print(f"Error generating script: {e}")
            return f"Error: Could not generate script for prompt: '{prompt}'"

    def _extract_keywords(self, script: str) -> List[str]:
        """
        Extracts key visual keywords from a script for sourcing stock footage.
        This is a simplified implementation. A more advanced version could use another LLM call.

        Args:
            script: The video script generated by the LLM.

        Returns:
            A list of keywords.
        """
        # A simple implementation for now. This can be improved with NLP libraries or an LLM call.
        # We will look for words that are likely to have good visual representations.
        
        # A predefined list of common but less useful words to ignore.
        stop_words = set([
            "a", "an", "the", "and", "but", "or", "in", "on", "at", "to", "for", "of",
            "is", "are", "was", "were", "be", "being", "been", "this", "that", "it",
            "you", "he", "she", "we", "they", "what", "why", "how", "when", "where",
            "video", "make", "create", "about", "facts", "top", "benefits"
        ])
        
        words = script.lower().split()
        keywords = [word.strip(".,!?") for word in words if word.strip(".,!?") not in stop_words and len(word.strip(".,!?")) > 3]
        
        # Return a unique, ordered list of the most frequent keywords
        from collections import Counter
        most_common = [word for word, count in Counter(keywords).most_common(10)]
        return most_common